DROP TABLE V_PARTY_COMMON;
CREATE TABLE V_PARTY_COMMON ( VALIDATION_NAME NVARCHAR2(1000), RECORD_COUNT NUMBER);
DROP TABLE V_PARTY_PERSON_DETAILS;
CREATE TABLE V_PARTY_PERSON_DETAILS ( VALIDATION_NAME NVARCHAR2(1000), RECORD_COUNT NUMBER);
